import {
  Bike,
  Car,
  Flame,
  Paintbrush,
  Scissors,
  TowerControl,
  Truck,
  Wrench,
  AlignVerticalJustifyCenter,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import {
  CHECKLIST_ALINEADORES_SUBMENU_ID,
  CHECKLIST_CABINA_PINTURA_SUBMENU_ID,
  CHECKLIST_ELEVADORES_SUBMENU_ID,
  CHECKLIST_HIDRAULICOS_SUBMENU_ID,
  CHECKLIST_MOTOCICLETAS_SUBMENU_ID,
  CHECKLIST_PORTICO_SUBMENU_ID,
  CHECKLIST_TIJERA_SUBMENU_ID,
  CHECKLIST_TRABAJO_CALIENTE_SUBMENU_ID,
  CHECKLIST_VEHICULO_SUBMENU_ID,
} from '@/utils/constants';

export const CHECKLIST_HUB_ITEMS: HubItem[] = [
  {
    id: 'motocicletas',
    nombre: 'Motocicletas',
    descripcion: 'Checklist de motocicletas (sistema ventas)',
    ruta: 'https://intranet.codiesel.co/ventas/CheckMoto',
    submenuId: CHECKLIST_MOTOCICLETAS_SUBMENU_ID,
    icono: Bike,
    color: 'from-teal-600 to-teal-700',
    external: true,
  },
  {
    id: 'vehiculo',
    nombre: 'Vehículo',
    descripcion: 'Checklist de vehículos (sistema ventas)',
    ruta: 'https://intranet.codiesel.co/ventas/CheckCarro',
    submenuId: CHECKLIST_VEHICULO_SUBMENU_ID,
    icono: Car,
    color: 'from-sky-600 to-sky-700',
    external: true,
  },
  {
    id: 'alineadores',
    nombre: 'Alineadores',
    descripcion: 'Inspección preoperacional del elevador del alineador',
    ruta: '/dashboard/checklist/alineadores',
    submenuId: CHECKLIST_ALINEADORES_SUBMENU_ID,
    icono: AlignVerticalJustifyCenter,
    color: 'from-blue-600 to-blue-700',
  },
  {
    id: 'elevadores',
    nombre: 'Elevadores',
    descripcion: 'Inspección preoperacional de elevadores de columna',
    ruta: '/dashboard/checklist/elevadores',
    submenuId: CHECKLIST_ELEVADORES_SUBMENU_ID,
    icono: TowerControl,
    color: 'from-indigo-600 to-indigo-700',
  },
  {
    id: 'hidraulicos',
    nombre: 'Hidráulicos',
    descripcion: 'Inspección preoperacional de equipos hidráulicos',
    ruta: '/dashboard/checklist/hidraulicos',
    submenuId: CHECKLIST_HIDRAULICOS_SUBMENU_ID,
    icono: Wrench,
    color: 'from-violet-600 to-violet-700',
  },
  {
    id: 'trabajo-caliente',
    nombre: 'Trabajo en Caliente',
    descripcion: 'Permiso y checklist de trabajo en caliente',
    ruta: '/dashboard/checklist/trabajo-caliente',
    submenuId: CHECKLIST_TRABAJO_CALIENTE_SUBMENU_ID,
    icono: Flame,
    color: 'from-orange-600 to-orange-700',
  },
  {
    id: 'portico',
    nombre: 'Pórtico',
    descripcion: 'Inspección preoperacional de pórtico con diferencial',
    ruta: '/dashboard/checklist/portico',
    submenuId: CHECKLIST_PORTICO_SUBMENU_ID,
    icono: Truck,
    color: 'from-amber-600 to-amber-700',
  },
  {
    id: 'tijera',
    nombre: 'Tijera',
    descripcion: 'Inspección preoperacional de elevadores tijera',
    ruta: '/dashboard/checklist/tijera',
    submenuId: CHECKLIST_TIJERA_SUBMENU_ID,
    icono: Scissors,
    color: 'from-lime-600 to-lime-700',
  },
  {
    id: 'cabina-pintura',
    nombre: 'Cabina de Pintura',
    descripcion: 'Inspección preoperacional de cabina de pintura',
    ruta: '/dashboard/checklist/cabina-pintura',
    submenuId: CHECKLIST_CABINA_PINTURA_SUBMENU_ID,
    icono: Paintbrush,
    color: 'from-pink-600 to-pink-700',
  },
];
