import {
  BarChart3,
  Building2,
  CalendarDays,
  Car,
  ClipboardList,
  Factory,
  FileWarning,
  Receipt,
  RotateCcw,
  UserCog,
  Wrench,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import {
  CODIESEL_EMPRESA_ID,
  CONTROL_ORDENES_DIARIAS_SUBMENU_ID,
  ENTREGAS_AUDITORIA_SUBMENU_ID,
  FACTURACION_TALLER_SUBMENU_ID,
  FACTURACION_TECNICO_SUBMENU_ID,
  NPS_FABRICA_SUBMENU_ID,
  ORDENES_MTTO_PREVENTIVO_SUBMENU_ID,
  ORDENES_TECNICOS_SUBMENU_ID,
  PQR_AUDITORIA_SUBMENU_ID,
  RANKING_NPS_TECNICOS_SUBMENU_ID,
  RETORNOS_POR_SEDE_SUBMENU_ID,
} from '@/utils/constants';

export const AUDITORIA_HUB_ITEMS: HubItem[] = [
  {
    id: 'ranking-nps-tecnicos',
    nombre: 'Ranking NPS Técnicos',
    descripcion: 'Órdenes finalizadas vs encuestas realizadas',
    ruta: '/dashboard/auditoria/ranking-nps-tecnicos',
    submenuId: RANKING_NPS_TECNICOS_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: BarChart3,
  },
  {
    id: 'control-ordenes-diarias',
    nombre: 'Control de Órdenes Diarias',
    descripcion: 'Tipificación de órdenes por bodega y fecha',
    ruta: '/dashboard/auditoria/ordenes-diarias',
    submenuId: CONTROL_ORDENES_DIARIAS_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: CalendarDays,
  },
  {
    id: 'retornos-por-sede',
    nombre: 'Retornos por Sede',
    descripcion: 'Comparativo entradas, retornos y posibles retornos',
    ruta: '/dashboard/auditoria/retornos-por-sede',
    submenuId: RETORNOS_POR_SEDE_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: RotateCcw,
  },
  {
    id: 'pqr',
    nombre: 'PQR',
    descripcion: 'Gestión de PQR y NPS de distintas fuentes',
    ruta: '/dashboard/auditoria/pqr',
    submenuId: PQR_AUDITORIA_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: FileWarning,
  },
  {
    id: 'nps-fabrica',
    nombre: 'NPS Fábrica',
    descripcion: 'Informe NPS Colmotores por sede y técnico',
    ruta: '/dashboard/auditoria/nps-fabrica',
    submenuId: NPS_FABRICA_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: Factory,
  },
  {
    id: 'ordenes-mtto-preventivo',
    nombre: 'Órdenes mtto preventivo vs presupuesto',
    descripcion: 'Cumplimiento de OT preventivas vs presupuesto',
    ruta: '/dashboard/auditoria/ordenes-mtto-preventivo',
    submenuId: ORDENES_MTTO_PREVENTIVO_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: Wrench,
  },
  {
    id: 'facturacion-taller',
    nombre: 'Facturación taller vs presupuesto',
    descripcion: 'Ventas vs presupuesto por sede (últimos meses)',
    ruta: '/dashboard/auditoria/facturacion-taller',
    submenuId: FACTURACION_TALLER_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: Building2,
  },
  {
    id: 'facturacion-tecnico',
    nombre: 'Facturación técnico vs presupuesto',
    descripcion: 'Ventas vs presupuesto por técnico',
    ruta: '/dashboard/auditoria/facturacion-tecnico',
    submenuId: FACTURACION_TECNICO_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: UserCog,
  },
  {
    id: 'ordenes-tecnicos',
    nombre: 'Órdenes técnicos vs presupuesto',
    descripcion: 'Cantidad de órdenes vs presupuesto por técnico',
    ruta: '/dashboard/auditoria/ordenes-tecnicos',
    submenuId: ORDENES_TECNICOS_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: ClipboardList,
  },
  {
    id: 'entregas',
    nombre: 'Entregas',
    descripcion: 'Entregas y segunda entrega por tipo de vehículo',
    ruta: '/dashboard/auditoria/entregas',
    submenuId: ENTREGAS_AUDITORIA_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: Car,
  },
];
