/** PHP `informe_formato_ordenSalida/index.php` — combos extra de Azucena/Daniel. */

export const NITS_FILTROS_EXTRA = [63369607, 1098679322] as const;

export const JEFES_FILTRO_ORDEN_SALIDA: { value: string; label: string }[] = [
  { value: '91274670', label: 'Carlos Enrique Lozano Galvis' },
  { value: '1005157209', label: 'Johan Sebastian Garcia Plata' },
  { value: '80872884', label: 'Juan Pablo Mier Avila' },
  { value: '1095932191', label: 'Oscar Fernando Ferrer Castro' },
  { value: '84109954', label: 'Luis Emilio Puche Aguirre' },
  { value: '1065913432', label: 'Manuelita Baleta Mauris' },
  { value: '1090449765', label: 'Karol Julieth Gomez Orozco' },
  { value: '1092358562', label: 'Zulay Villalba Toloza' },
  { value: '1094532250', label: 'Oscar Emilio Romero Urbina' },
  { value: '91259929', label: 'Edgar Mauricio Galvis Tavera' },
  { value: '1095913265', label: 'Cesar Augusto Caicedo Caycedo' },
  { value: '1092355065', label: 'David Davila' },
  { value: '1096957166', label: 'Sergio Andres Gomez Matajira' },
  { value: '1090484563', label: 'Karen Michelle Barbosa Carvajal' },
  { value: '13741590', label: 'Juan Alexander Calderon Blanco' },
  { value: '63368988', label: 'Liliana Cristancho Ferreira' },
  { value: '91525308', label: 'Elkin Alexander Velasquez Albarracin' },
  { value: '1014178302', label: 'Nelson Jose Diaz Rodriguez' },
  { value: '1098739531', label: 'Andrea Patricia Parra Ayala' },
  { value: '1095809978', label: 'Joseph Dayron Muñoz Gomez' },
  { value: '91297508', label: 'Wilson Fiallo Santander' },
  { value: '91510897', label: 'Cesar Augusto Dominguez Mosquera' },
  { value: '1093736472', label: 'Deysi Lorena Leon Montañez' },
  { value: '1095816177', label: 'Gomez Uribe Daniela' },
  { value: '79984087', label: 'Oscar Mauricio Tapias Pinto' },
  { value: '1091655270', label: 'Eneida Perez Rojas' },
  { value: '1098625558', label: 'Zuly Nathalia Ramirez Burgos' },
  { value: '1099367783', label: 'Erika Lizeth Aguilar Herrera' },
  { value: '1128465895', label: 'Jaime Andres Martinez Barrios' },
  { value: '1099372035', label: 'Darly Lizeth Cadena Regueros' },
  { value: '1004967243', label: 'Garzon Castro Ingrid Lucero' },
  { value: '28070692', label: 'Diana Lizette Hernandez Tovar' },
  { value: '1093791359', label: 'Quintero Romero Estefany Yajaira' },
  { value: '1090497067', label: 'Forero Carrero Heidy Esmeralda' },
  { value: '37579713', label: 'Rueda Romero Irene Isabel' },
  { value: '1094241876', label: 'Burgos Ramirez Gabriel Felipe' },
  { value: '79145617', label: 'Jorge Humberto Franco Rugeles' },
  { value: '1092338001', label: 'Andrea Paola Ramirez Ramirez' },
  { value: '1098679322', label: 'Daniel Felipe Gonzalez Rueda' },
  { value: '63289710', label: 'Yolanda Quintero Ortiz' },
  { value: '63369607', label: 'Azucena Franco Gomez' },
  { value: '91298113', label: 'Orlando Duran Serrano' },
];

export const AREAS_FILTRO_ORDEN_SALIDA: { value: string; label: string }[] = [
  { value: 'Administración', label: 'Administración' },
  { value: 'Central de Beneficios', label: 'Central de Beneficios' },
  { value: 'Vehiculos Nuevos', label: 'Vehículos Nuevos' },
  { value: 'Vehiculos Usados', label: 'Vehículos Usados' },
  { value: 'Repuestos', label: 'Repuestos' },
  { value: 'Taller Gasolina', label: 'Taller Gasolina' },
  { value: 'Taller Diesel', label: 'Taller Diesel' },
  { value: 'Lamina y Pintura', label: 'Lamina y Pintura' },
  { value: 'Alistamiento', label: 'Alistamiento' },
  { value: 'Contact Center', label: 'Contact Center' },
  { value: 'Accesorios', label: 'Accesorios' },
];

export const SEDES_FILTRO_ORDEN_SALIDA: { value: string; label: string }[] = [
  { value: 'Giron', label: 'Girón' },
  { value: 'Rosita', label: 'Rosita' },
  { value: 'Bocono', label: 'Bocono' },
  { value: 'Malecon', label: 'Malecon' },
  { value: 'Barranca', label: 'Barranca' },
  { value: 'Otra', label: 'Otra' },
];

export const TIPOS_FILTRO_ORDEN_SALIDA: { value: number; label: string }[] = [
  { value: 1, label: 'VH Taller entregado a cliente' },
  { value: 2, label: 'Repuestos' },
  { value: 3, label: 'Cuatrinario SPV019' },
  { value: 4, label: 'N400 WOM803' },
  { value: 5, label: 'Niñera TAV656' },
  { value: 6, label: 'N300 TTR469' },
  { value: 7, label: 'NHR XMB415' },
  { value: 8, label: 'VH Usado' },
  { value: 9, label: 'Material Publicitario' },
  { value: 10, label: 'Test Drive' },
  { value: 11, label: 'Equipo de Sistemas' },
  { value: 12, label: 'VH Accesorizados' },
  { value: 13, label: 'Objetos Varios' },
  { value: 14, label: 'Mobiliario' },
  { value: 15, label: 'VH Nuevos para entrega' },
  { value: 16, label: 'VH Taller prueba de ruta' },
  { value: 17, label: 'VH Nuevos sin placa' },
  { value: 18, label: 'Vehículos disposición residuos' },
];
