import {
  AlertCircle,
  BookOpen,
  Calculator,
  Calendar,
  CalendarDays,
  Car,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  Receipt,
  Shirt,
  ShoppingCart,
  TrendingUp,
  UserCheck,
  UserX,
  Users,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';

export const ADMINISTRACION_HUB_ITEMS: HubItem[] = [
  {
    id: 'ajustes-valores',
    nombre: 'Ajustes Valores Contables',
    descripcion: 'Gestión y ajuste de valores contables multiempresa',
    ruta: '/dashboard/administracion/ajustes-valores-contables',
    submenuId: 178,
    icono: Calculator,
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 'control-vehiculos',
    nombre: 'Control Ingreso y Salida de Vehículos',
    descripcion: 'Registro y control de ingresos y salidas de vehículos',
    ruta: '/dashboard/administracion/control-vehiculos',
    submenuId: 190,
    icono: Car,
    color: 'from-green-500 to-green-600',
  },
  {
    id: 'evaluacion-desempeno',
    nombre: 'Evaluación Desempeño Empleado',
    descripcion: 'Evaluación de desempeño por jefe inmediato',
    ruta: '/dashboard/administracion/evaluacion-desempeno',
    submenuId: 153,
    icono: UserCheck,
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 'formato-desempeno',
    nombre: 'Formato Desempeño Empleado',
    descripcion: 'Autoevaluación de desempeño por empleado',
    ruta: '/dashboard/administracion/formato-desempeno-empleado',
    submenuId: 152,
    icono: FileText,
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 'formato-orden-salida',
    nombre: 'Formato Orden de Salida',
    descripcion: 'Consulta de órdenes de salida por placa',
    ruta: '/dashboard/administracion/formato-orden-salida',
    submenuId: 154,
    icono: ClipboardList,
    color: 'from-stone-500 to-stone-600',
  },
  {
    id: 'formatos-nomina',
    nombre: 'Formatos Nómina',
    descripcion: 'Consulta, visualiza y descarga los formatos de nómina vigentes',
    ruta: '/dashboard/administracion/formatos-nomina',
    submenuId: 184,
    icono: Receipt,
    color: 'from-amber-500 to-amber-600',
  },
  {
    id: 'gestion-compras',
    nombre: 'Gestión de Compras',
    descripcion: 'Solicitudes y gestión de compras multiempresa',
    ruta: '/dashboard/administracion/gestion-compras',
    submenuId: 79,
    icono: ShoppingCart,
    color: 'from-orange-500 to-orange-600',
  },
  {
    id: 'inasistencia',
    nombre: 'Inasistencia',
    descripcion: 'Informe de inasistencia de empleados',
    ruta: '/dashboard/administracion/inasistencia',
    submenuId: 126,
    icono: UserX,
    color: 'from-red-500 to-red-600',
  },
  {
    id: 'informe-ausentismo',
    nombre: 'Informe Ausentismo',
    descripcion: 'Informe detallado de ausentismo multiempresa',
    ruta: '/dashboard/administracion/informe-ausentismo',
    submenuId: 45,
    icono: Calendar,
    color: 'from-pink-500 to-pink-600',
  },
  {
    id: 'informe-sostenibilidad',
    nombre: 'Informe de Sostenibilidad 2024',
    descripcion: 'Visualización del informe de sostenibilidad',
    ruta: '/dashboard/administracion/informe-sostenibilidad',
    submenuId: 189,
    icono: FileCheck,
    color: 'from-emerald-500 to-emerald-600',
  },
  {
    id: 'informe-tiempo-suplementario',
    nombre: 'Informe Tiempo Suplementario',
    descripcion: 'Informe de tiempo suplementario multiempresa',
    ruta: '/dashboard/administracion/informe-tiempo-suplementario',
    submenuId: 57,
    icono: Clock,
    color: 'from-cyan-500 to-cyan-600',
  },
  {
    id: 'lista-ausentismo',
    nombre: 'Lista Ausentismo',
    descripcion: 'Ausentismos del día actual',
    ruta: '/dashboard/administracion/lista-ausentismo',
    submenuId: 62,
    icono: CalendarDays,
    color: 'from-rose-500 to-rose-600',
  },
  {
    id: 'lista-horas-extras',
    nombre: 'Lista Horas Extras',
    descripcion: 'Horas extras del día actual',
    ruta: '/dashboard/administracion/lista-horas-extras',
    submenuId: 61,
    icono: TrendingUp,
    color: 'from-teal-500 to-teal-600',
  },
  {
    id: 'nuevo-ausentismo',
    nombre: 'Nuevo Ausentismo',
    descripcion: 'Registro de nuevos ausentismos',
    ruta: '/dashboard/administracion/nuevo-ausentismo',
    submenuId: 44,
    icono: AlertCircle,
    color: 'from-violet-500 to-violet-600',
  },
  {
    id: 'solicitud-tiempo-suplementario',
    nombre: 'Solicitud Tiempo Suplementario',
    descripcion: 'Solicitud de tiempo suplementario',
    ruta: '/dashboard/administracion/solicitud-tiempo-suplementario',
    submenuId: 56,
    icono: Users,
    color: 'from-sky-500 to-sky-600',
  },
  {
    id: 'tallas-dotacion',
    nombre: 'Tallas Dotación',
    descripcion: 'Actualización de tallas para dotación',
    ruta: '/dashboard/administracion/tallas-dotacion',
    submenuId: 155,
    icono: Shirt,
    color: 'from-lime-500 to-lime-600',
  },
  {
    id: 'reglamento-interno',
    nombre: 'Reglamento Interno de Trabajo',
    descripcion: 'Consulta del reglamento interno',
    ruta: '/dashboard/administracion/reglamento-interno',
    submenuId: 172,
    icono: BookOpen,
    color: 'from-slate-500 to-slate-600',
  },
];
