import {
  AlertCircle,
  BookOpen,
  Calculator,
  Calendar,
  CalendarDays,
  Car,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  Receipt,
  Shirt,
  ShoppingCart,
  TrendingUp,
  UserCheck,
  UserX,
  Users,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import {
  AJUSTES_VALORES_CONTABLES_SUBMENU_ID,
  CONTROL_VEHICULOS_SUBMENU_ID,
  EVALUACION_DESEMPENO_SUBMENU_ID,
  FORMATO_DESEMPENO_EMPLEADO_SUBMENU_ID,
  FORMATO_ORDEN_SALIDA_SUBMENU_ID,
  FORMATOS_NOMINA_SUBMENU_ID,
  GESTION_COMPRAS_SUBMENU_ID,
  INASISTENCIA_SUBMENU_ID,
  INFORME_AUSENTISMO_SUBMENU_ID,
  INFORME_SOSTENIBILIDAD_SUBMENU_ID,
  INFORME_TIEMPO_SUPLEMENTARIO_SUBMENU_ID,
  LISTA_AUSENTISMO_SUBMENU_ID,
  LISTA_HORAS_EXTRAS_SUBMENU_ID,
  NUEVO_AUSENTISMO_SUBMENU_ID,
  REGLAMENTO_INTERNO_SUBMENU_ID,
  SOLICITUD_TIEMPO_SUPLEMENTARIO_SUBMENU_ID,
  TALLAS_DOTACION_SUBMENU_ID,
} from '@/utils/constants';

export const ADMINISTRACION_HUB_ITEMS: HubItem[] = [
  {
    id: 'ajustes-valores',
    nombre: 'Ajustes Valores Contables',
    descripcion: 'Gestión y ajuste de valores contables multiempresa',
    ruta: '/dashboard/administracion/ajustes-valores-contables',
    submenuId: AJUSTES_VALORES_CONTABLES_SUBMENU_ID,
    icono: Calculator,
  },
  {
    id: 'control-vehiculos',
    nombre: 'Control Ingreso y Salida de Vehículos',
    descripcion: 'Registro y control de ingresos y salidas de vehículos',
    ruta: '/dashboard/administracion/control-vehiculos',
    submenuId: CONTROL_VEHICULOS_SUBMENU_ID,
    icono: Car,
  },
  {
    id: 'evaluacion-desempeno',
    nombre: 'Evaluación Desempeño Empleado',
    descripcion: 'Evaluación de desempeño por jefe inmediato',
    ruta: '/dashboard/administracion/evaluacion-desempeno',
    submenuId: EVALUACION_DESEMPENO_SUBMENU_ID,
    icono: UserCheck,
  },
  {
    id: 'formato-desempeno',
    nombre: 'Formato Desempeño Empleado',
    descripcion: 'Autoevaluación de desempeño por empleado',
    ruta: '/dashboard/administracion/formato-desempeno-empleado',
    submenuId: FORMATO_DESEMPENO_EMPLEADO_SUBMENU_ID,
    icono: FileText,
  },
  {
    id: 'formato-orden-salida',
    nombre: 'Formato Orden de Salida',
    descripcion: 'Registro del formato de orden de salida (SGC-FR02)',
    ruta: '/dashboard/administracion/formato-orden-salida',
    submenuId: FORMATO_ORDEN_SALIDA_SUBMENU_ID,
    icono: ClipboardList,
  },
  {
    id: 'formatos-nomina',
    nombre: 'Formatos Nómina',
    descripcion: 'Consulta, visualiza y descarga los formatos de nómina vigentes',
    ruta: '/dashboard/administracion/formatos-nomina',
    submenuId: FORMATOS_NOMINA_SUBMENU_ID,
    icono: Receipt,
  },
  {
    id: 'gestion-compras',
    nombre: 'Gestión de Compras',
    descripcion: 'Solicitudes y gestión de compras multiempresa',
    ruta: '/dashboard/administracion/gestion-compras',
    submenuId: GESTION_COMPRAS_SUBMENU_ID,
    icono: ShoppingCart,
  },
  {
    id: 'inasistencia',
    nombre: 'Inasistencia',
    descripcion: 'Informe de inasistencia de empleados',
    ruta: '/dashboard/administracion/inasistencia',
    submenuId: INASISTENCIA_SUBMENU_ID,
    icono: UserX,
  },
  {
    id: 'informe-ausentismo',
    nombre: 'Informe Ausentismo',
    descripcion: 'Informe detallado de ausentismo multiempresa',
    ruta: '/dashboard/administracion/informe-ausentismo',
    submenuId: INFORME_AUSENTISMO_SUBMENU_ID,
    icono: Calendar,
  },
  {
    id: 'informe-sostenibilidad',
    nombre: 'Informe de Sostenibilidad 2024',
    descripcion: 'Visualización del informe de sostenibilidad',
    ruta: '/dashboard/administracion/informe-sostenibilidad',
    submenuId: INFORME_SOSTENIBILIDAD_SUBMENU_ID,
    icono: FileCheck,
  },
  {
    id: 'informe-tiempo-suplementario',
    nombre: 'Informe Tiempo Suplementario',
    descripcion: 'Informe de tiempo suplementario multiempresa',
    ruta: '/dashboard/administracion/informe-tiempo-suplementario',
    submenuId: INFORME_TIEMPO_SUPLEMENTARIO_SUBMENU_ID,
    icono: Clock,
  },
  {
    id: 'lista-ausentismo',
    nombre: 'Lista Ausentismo',
    descripcion: 'Ausentismos del día actual',
    ruta: '/dashboard/administracion/lista-ausentismo',
    submenuId: LISTA_AUSENTISMO_SUBMENU_ID,
    icono: CalendarDays,
  },
  {
    id: 'lista-horas-extras',
    nombre: 'Lista Horas Extras',
    descripcion: 'Horas extras del día actual',
    ruta: '/dashboard/administracion/lista-horas-extras',
    submenuId: LISTA_HORAS_EXTRAS_SUBMENU_ID,
    icono: TrendingUp,
  },
  {
    id: 'nuevo-ausentismo',
    nombre: 'Nuevo Ausentismo',
    descripcion: 'Registro de nuevos ausentismos',
    ruta: '/dashboard/administracion/nuevo-ausentismo',
    submenuId: NUEVO_AUSENTISMO_SUBMENU_ID,
    icono: AlertCircle,
  },
  {
    id: 'solicitud-tiempo-suplementario',
    nombre: 'Solicitud Tiempo Suplementario',
    descripcion: 'Solicitud de tiempo suplementario',
    ruta: '/dashboard/administracion/solicitud-tiempo-suplementario',
    submenuId: SOLICITUD_TIEMPO_SUPLEMENTARIO_SUBMENU_ID,
    icono: Users,
  },
  {
    id: 'tallas-dotacion',
    nombre: 'Tallas Dotación',
    descripcion: 'Actualización de tallas para dotación',
    ruta: '/dashboard/administracion/tallas-dotacion',
    submenuId: TALLAS_DOTACION_SUBMENU_ID,
    icono: Shirt,
  },
  {
    id: 'reglamento-interno',
    nombre: 'Reglamento Interno de Trabajo',
    descripcion: 'Consulta del reglamento interno',
    ruta: '/dashboard/administracion/reglamento-interno',
    submenuId: REGLAMENTO_INTERNO_SUBMENU_ID,
    icono: BookOpen,
  },
];
