import {
  AlertCircle,
  BookOpen,
  Calculator,
  Calendar,
  CalendarDays,
  Car,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  Receipt,
  Shirt,
  ShoppingCart,
  TrendingUp,
  UserCheck,
  UserX,
  Users,
} from 'lucide-react';
import { attachHubIcons } from '@/components/shared/hub/attach-hub-icons';
import { ADMINISTRACION_HUB_NAV } from './nav';

export const ADMINISTRACION_HUB_ITEMS = attachHubIcons(ADMINISTRACION_HUB_NAV, {
  'ajustes-valores': Calculator,
  'control-vehiculos': Car,
  'evaluacion-desempeno': UserCheck,
  'formato-desempeno': FileText,
  'formato-orden-salida': ClipboardList,
  'formatos-nomina': Receipt,
  'gestion-compras': ShoppingCart,
  'inasistencia': UserX,
  'informe-ausentismo': Calendar,
  'informe-sostenibilidad': FileCheck,
  'informe-tiempo-suplementario': Clock,
  'lista-ausentismo': CalendarDays,
  'lista-horas-extras': TrendingUp,
  'nuevo-ausentismo': AlertCircle,
  'solicitud-tiempo-suplementario': Users,
  'tallas-dotacion': Shirt,
  'reglamento-interno': BookOpen,
});
