import { FileBarChart2, MessageCircle, SmilePlus, Users } from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import { INFORMES_COPY, INFORMES_PV_TRIMENU } from '@/modules/informes/constants';

export const POSTVENTA_HUB_ITEMS: HubItem[] = [
  {
    id: 'llegada-vehiculos',
    nombre: INFORMES_COPY.llegadaVehiculos.title,
    descripcion: INFORMES_COPY.llegadaVehiculos.description,
    ruta: '/dashboard/informes/postventa/llegada-vehiculos',
    trimenuId: INFORMES_PV_TRIMENU.llegadaVehiculos,
    icono: FileBarChart2,
  },
  {
    id: 'ventas-1a1',
    nombre: INFORMES_COPY.ventas1a1.title,
    descripcion: INFORMES_COPY.ventas1a1.description,
    ruta: '/dashboard/informes/postventa/ventas-1a1',
    trimenuId: INFORMES_PV_TRIMENU.ventas1a1,
    icono: FileBarChart2,
  },
  {
    id: 'tiempo-entrevista-consultiva',
    nombre: INFORMES_COPY.tiempoEntrevista.title,
    descripcion: INFORMES_COPY.tiempoEntrevista.description,
    ruta: '/dashboard/informes/postventa/tiempo-entrevista-consultiva',
    trimenuId: INFORMES_PV_TRIMENU.tiempoEntrevista,
    icono: FileBarChart2,
  },
  {
    id: 'inventario-obsoletos',
    nombre: INFORMES_COPY.inventarioObsoletos.title,
    descripcion: INFORMES_COPY.inventarioObsoletos.description,
    ruta: '/dashboard/informes/postventa/inventario-obsoletos',
    trimenuId: INFORMES_PV_TRIMENU.inventarioObsoletos,
    icono: FileBarChart2,
  },
  {
    id: 'ticket-promedio-tecnico',
    nombre: INFORMES_COPY.ticketPromedio.title,
    descripcion: INFORMES_COPY.ticketPromedio.description,
    ruta: '/dashboard/informes/postventa/ticket-promedio-tecnico',
    trimenuId: INFORMES_PV_TRIMENU.ticketPromedio,
    icono: FileBarChart2,
  },
  {
    id: 'kpi',
    nombre: INFORMES_COPY.kpi.title,
    descripcion: INFORMES_COPY.kpi.description,
    ruta: '/dashboard/informes/postventa/kpi',
    trimenuId: INFORMES_PV_TRIMENU.kpi,
    trimenuIdsAlternativos: [INFORMES_PV_TRIMENU.kpiAlt],
    icono: FileBarChart2,
  },
  {
    id: 'segunda-entrega',
    nombre: INFORMES_COPY.segundaEntrega.title,
    descripcion: INFORMES_COPY.segundaEntrega.description,
    ruta: '/dashboard/informes/postventa/segunda-entrega',
    trimenuId: INFORMES_PV_TRIMENU.segundaEntrega,
    icono: FileBarChart2,
  },
  {
    id: 'retencion-72-0',
    nombre: INFORMES_COPY.retencion72.title,
    descripcion: INFORMES_COPY.retencion72.description,
    ruta: '/dashboard/informes/postventa/retencion-72-0',
    trimenuId: INFORMES_PV_TRIMENU.retencion72,
    icono: FileBarChart2,
  },
  {
    id: 'nps-interno',
    nombre: INFORMES_COPY.npsInterno.title,
    descripcion: INFORMES_COPY.npsInterno.description,
    ruta: '/dashboard/informes/postventa/nps-interno',
    trimenuId: INFORMES_PV_TRIMENU.npsInterno,
    icono: FileBarChart2,
  },
  {
    id: 'productividad-tecnicos',
    nombre: INFORMES_COPY.productividadTecnicos.title,
    descripcion: INFORMES_COPY.productividadTecnicos.description,
    ruta: '/dashboard/informes/postventa/productividad-tecnicos',
    trimenuId: INFORMES_PV_TRIMENU.productividadTecnicos,
    icono: FileBarChart2,
  },
  {
    id: 'nps-tecnicos',
    nombre: INFORMES_COPY.npsTecnicos.title,
    descripcion: INFORMES_COPY.npsTecnicos.description,
    ruta: '/dashboard/informes/postventa/nps-tecnicos',
    trimenuId: INFORMES_PV_TRIMENU.npsTecnicos,
    icono: Users,
  },
  {
    id: 'mpc',
    nombre: INFORMES_COPY.mpc.title,
    descripcion: INFORMES_COPY.mpc.description,
    ruta: '/dashboard/informes/postventa/mpc',
    trimenuId: INFORMES_PV_TRIMENU.mpc,
    icono: FileBarChart2,
  },
  {
    id: 'encuesta-satisfaccion',
    nombre: INFORMES_COPY.encuestaSatisfaccion.title,
    descripcion: INFORMES_COPY.encuestaSatisfaccion.description,
    ruta: '/dashboard/informes/postventa/encuesta-satisfaccion',
    trimenuId: INFORMES_PV_TRIMENU.encuestaSatisfaccion,
    icono: SmilePlus,
  },
  {
    id: 'pqr-nps',
    nombre: INFORMES_COPY.pqrNps.title,
    descripcion: INFORMES_COPY.pqrNps.description,
    ruta: '/dashboard/informes/postventa/pqr-nps',
    trimenuId: INFORMES_PV_TRIMENU.pqrNps,
    icono: MessageCircle,
  },
  {
    id: 'pac-nps-interno-detallado',
    nombre: INFORMES_COPY.pacNpsDetallado.title,
    descripcion: INFORMES_COPY.pacNpsDetallado.description,
    ruta: '/dashboard/informes/postventa/pac-nps-interno-detallado',
    trimenuId: INFORMES_PV_TRIMENU.pacNpsDetallado,
    icono: FileBarChart2,
  },
  {
    id: 'pac',
    nombre: INFORMES_COPY.pac.title,
    descripcion: INFORMES_COPY.pac.description,
    ruta: '/dashboard/informes/postventa/pac',
    trimenuId: INFORMES_PV_TRIMENU.pac,
    icono: FileBarChart2,
  },
  {
    id: 'panel-nps',
    nombre: INFORMES_COPY.panelNps.title,
    descripcion: INFORMES_COPY.panelNps.description,
    ruta: '/dashboard/informes/postventa/panel-nps',
    trimenuId: INFORMES_PV_TRIMENU.panelNps,
    icono: FileBarChart2,
  },
  {
    id: 'encuestas-internas',
    nombre: INFORMES_COPY.encuestasInternas.title,
    descripcion: INFORMES_COPY.encuestasInternas.description,
    ruta: '/dashboard/informes/postventa/encuestas-internas',
    trimenuId: INFORMES_PV_TRIMENU.encuestasInternas,
    icono: MessageCircle,
  },
];
