import {
  AlertTriangle,
  Car,
  ClipboardList,
  Edit3,
  FileBarChart,
  Layers,
  PlusCircle,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';

export const COTIZAR_HUB_ITEMS: HubItem[] = [
  {
    id: 'livianos',
    nombre: 'Livianos',
    descripcion: 'Cotizador de mantenimiento y repuestos para vehículos livianos.',
    ruta: '/dashboard/cotizar/livianos',
    submenuId: 90,
    icono: Car,
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 'informe-cotizaciones',
    nombre: 'Informe de cotizaciones',
    descripcion: 'Consulta histórica y analítica de cotizaciones generadas.',
    ruta: '/dashboard/cotizar/informe-cotizaciones',
    submenuId: 91,
    icono: FileBarChart,
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 'ejecucion-cotizado-vs-facturado',
    nombre: 'Ejecución Cotizado vs Facturado',
    descripcion: 'Comparativo entre lo cotizado y lo finalmente facturado.',
    ruta: '/dashboard/cotizar/ejecucion-cotizado-vs-facturado',
    submenuId: 110,
    icono: Layers,
    color: 'from-teal-500 to-teal-600',
  },
  {
    id: 'repuestos-no-disponibles',
    nombre: 'Repuestos no disponibles',
    descripcion: 'Control y seguimiento de repuestos no disponibles al momento de cotizar.',
    ruta: '/dashboard/cotizar/repuestos-no-disponibles',
    submenuId: 95,
    icono: AlertTriangle,
    color: 'from-amber-500 to-amber-600',
  },
  {
    id: 'control',
    nombre: 'Control',
    descripcion: 'Control detallado de repuestos y mano de obra asociados a las cotizaciones.',
    ruta: '/dashboard/cotizar/control',
    submenuId: 101,
    icono: ClipboardList,
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'adicionales-livianos',
    nombre: 'Adicionales Livianos',
    descripcion: 'Configuración de adicionales de repuestos y mano de obra para livianos.',
    ruta: '/dashboard/cotizar/adicionales-livianos',
    submenuId: 118,
    icono: PlusCircle,
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 'editar-repuesto-mano-obra',
    nombre: 'Editar repuesto / mano de obra',
    descripcion: 'Edición masiva de configuraciones de repuestos y mano de obra.',
    ruta: '/dashboard/cotizar/editar-repuesto-mano-obra',
    submenuId: 196,
    icono: Edit3,
    color: 'from-rose-500 to-rose-600',
  },
];
