import {
  CarFront,
  ClipboardCheck,
  ClipboardList,
  FileBarChart2,
  Headphones,
  RotateCcw,
  Settings,
  TrendingUp,
  Wallet,
  Wrench,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import {
  CODIESEL_EMPRESA_ID,
  ENTRADA_VEHICULO_SUBMENU_ID,
  ESTADO_TALLER_SUBMENU_ID,
  INFORME_OT_ABIERTAS_SUBMENU_ID,
  INFORME_POSIBLES_RETORNOS_SUBMENU_ID,
  MPVI_SUBMENU_IDS,
  POSIBLES_RETORNOS_SUBMENU_ID,
  PRESUPUESTO_SUBMENU_ID,
  PYG_ASESORES_REPUESTOS_SUBMENU_ID,
  PYG_TECNICOS_SUBMENU_ID,
} from '@/utils/constants';

export const TALLER_HUB_ITEMS: HubItem[] = [
  {
    id: 'estado-taller',
    nombre: 'Estado taller',
    descripcion: 'Órdenes abiertas, historial, valores estimados y seguimiento',
    ruta: '/dashboard/taller/estado-taller',
    submenuId: ESTADO_TALLER_SUBMENU_ID,
    icono: ClipboardCheck,
  },
  {
    id: 'informe-ordenes-abiertas',
    nombre: 'Informe órdenes taller',
    descripcion: 'Resumen por sede y detalle de órdenes de trabajo abiertas',
    ruta: '/dashboard/taller/informe-ordenes-abiertas',
    submenuId: INFORME_OT_ABIERTAS_SUBMENU_ID,
    icono: FileBarChart2,
  },
  {
    id: 'informe-posibles-retornos',
    nombre: 'Informe posibles retornos',
    descripcion: 'Gráfico comparativo de entradas, retornos y posibles retornos',
    ruta: '/dashboard/taller/informe-posibles-retornos',
    submenuId: INFORME_POSIBLES_RETORNOS_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: RotateCcw,
  },
  {
    id: 'posibles-retornos',
    nombre: 'Posibles retornos',
    descripcion: 'Gestión y seguimiento de posibles retornos en taller',
    ruta: '/dashboard/taller/posibles-retornos',
    submenuId: POSIBLES_RETORNOS_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: RotateCcw,
  },
  {
    id: 'pyg-asesores-repuestos',
    nombre: 'P&G Asesores de Repuestos',
    descripcion: 'Informe de utilidades por asesor con comparación anual',
    ruta: '/dashboard/taller/pyg-asesores-repuestos',
    submenuId: PYG_ASESORES_REPUESTOS_SUBMENU_ID,
    icono: TrendingUp,
  },
  {
    id: 'pyg-tecnicos',
    nombre: 'P&G Técnicos',
    descripcion: 'Informe de utilidades por técnico con comparación anual',
    ruta: '/dashboard/taller/pyg-tecnicos',
    submenuId: PYG_TECNICOS_SUBMENU_ID,
    icono: TrendingUp,
  },
  {
    id: 'presupuesto',
    nombre: 'Presupuesto',
    descripcion: 'Consulta y edición de presupuesto mensual por sede y categoría',
    ruta: '/dashboard/taller/presupuesto',
    submenuId: PRESUPUESTO_SUBMENU_ID,
    empresaId: CODIESEL_EMPRESA_ID,
    icono: Wallet,
  },
  {
    id: 'entrada-vehiculo',
    nombre: 'Entrada de vehículo',
    descripcion: 'Registro de ingreso al taller, citas y vehículos sin cita',
    ruta: '/dashboard/taller/entrada-vehiculo',
    submenuId: ENTRADA_VEHICULO_SUBMENU_ID,
    icono: CarFront,
  },
  {
    id: 'mpvi-admin',
    nombre: 'Administración MPVI',
    descripcion: 'Carga de plantillas y catálogos',
    ruta: '/dashboard/taller/mpvi/mpvi-admin',
    submenuId: MPVI_SUBMENU_IDS.admin,
    icono: Settings,
  },
  {
    id: 'mpvi-tecnicos',
    nombre: 'MPVI Técnicos',
    descripcion: 'Cotización MPVI por técnico de taller',
    ruta: '/dashboard/taller/mpvi/mpvi-tecnicos',
    submenuId: MPVI_SUBMENU_IDS.tecnicos,
    icono: Wrench,
  },
  {
    id: 'mpvi-jefe-taller',
    nombre: 'MPVI Jefe de Taller',
    descripcion: 'Autorización y gestión de servicios MPVI',
    ruta: '/dashboard/taller/mpvi/mpvi-jefe-taller',
    submenuId: MPVI_SUBMENU_IDS.jefeTaller,
    icono: ClipboardList,
  },
  {
    id: 'mpvi-contact',
    nombre: 'MPVI Contact',
    descripcion: 'Seguimiento de cotizaciones y contacto con clientes',
    ruta: '/dashboard/taller/mpvi/mpvi-contact',
    submenuId: MPVI_SUBMENU_IDS.contact,
    icono: Headphones,
  },
];
