import {
  Activity,
  Bike,
  CalendarRange,
  Car,
  ClipboardList,
  Clock,
  ListChecks,
  LogIn,
  LogOut,
  ShoppingCart,
  Truck,
  UserX,
  Wrench,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';

export const GESTION_HUMANA_HUB_ITEMS: HubItem[] = [
  {
    id: 'inf-ausentismos',
    nombre: 'Informe Tiempo de Ausentismos',
    descripcion: 'Consulta de tiempo de ausentismos por empleado y mes, con exportación a Excel.',
    ruta: '/dashboard/informes/gestion-humana/inf-ausentismos',
    trimenuId: 4,
    icono: CalendarRange,
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 'checklist-carro',
    nombre: 'Checklist Carro',
    descripcion: 'Informe detallado de checklist de vehículos por sede y fechas.',
    ruta: '/dashboard/informes/gestion-humana/checklist-carro',
    trimenuId: 35,
    icono: Car,
    color: 'from-sky-600 to-sky-700',
  },
  {
    id: 'checklist-moto',
    nombre: 'Checklist Moto',
    descripcion: 'Informe detallado de checklist de motos por sede y fechas.',
    ruta: '/dashboard/informes/gestion-humana/checklist-moto',
    trimenuId: 36,
    icono: Bike,
    color: 'from-teal-600 to-teal-700',
  },
  {
    id: 'control-compras',
    nombre: 'Control Compras',
    descripcion: 'Control de compras por número de orden con existencias por bodega.',
    ruta: '/dashboard/informes/gestion-humana/control-compras',
    trimenuId: 34,
    icono: ShoppingCart,
    color: 'from-amber-600 to-amber-700',
  },
  {
    id: 'indicador-checklist',
    nombre: 'Indicador Checklist',
    descripcion: 'Número de registros por sede para los diferentes checklists de equipos.',
    ruta: '/dashboard/informes/gestion-humana/indicador-checklist',
    trimenuId: 10,
    icono: ListChecks,
    color: 'from-lime-500 to-lime-600',
  },
  {
    id: 'indicador-checklist-pesv',
    nombre: 'Indicador Checklist PESV',
    descripcion: 'Número de registros de checklist PESV por placa y tipo de vehículo.',
    ruta: '/dashboard/informes/gestion-humana/indicador-checklist-pesv',
    trimenuId: 37,
    icono: ListChecks,
    color: 'from-lime-600 to-lime-700',
  },
  {
    id: 'checklists-equipos',
    nombre: 'Checklist Equipos',
    descripcion: 'Detalle de los diferentes checklists de equipos por rango de fechas.',
    ruta: '/dashboard/informes/gestion-humana/checklists',
    trimenuId: 38,
    icono: ListChecks,
    color: 'from-lime-700 to-lime-800',
  },
  {
    id: 'informe-ordenes-salida',
    nombre: 'Informe Órdenes de Salida',
    descripcion: 'Consulta y gestión de observaciones de las órdenes de salida.',
    ruta: '/dashboard/informes/gestion-humana/ordenes-salida',
    trimenuId: 44,
    icono: ClipboardList,
    color: 'from-orange-500 to-orange-600',
  },
  {
    id: 'tallas-personal',
    nombre: 'Tallas dotación',
    descripcion: 'Informe de tallas de camisa, pantalón y botas del personal.',
    ruta: '/dashboard/informes/gestion-humana/tallas-personal',
    trimenuId: 45,
    icono: ClipboardList,
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 'desempeno-empleado',
    nombre: 'Desempeño Empleado',
    descripcion: 'Informe de desempeño de empleados por año y sede.',
    ruta: '/dashboard/informes/gestion-humana/desempeno-empleado',
    trimenuId: 46,
    icono: ClipboardList,
    color: 'from-yellow-500 to-yellow-600',
  },
  {
    id: 'tiempo-gestion-compras',
    nombre: 'Tiempo Gestión Compras',
    descripcion: 'Informe de tiempos de gestión de compras por fecha y estado.',
    ruta: '/dashboard/informes/gestion-humana/tiempo-gestion-compras',
    trimenuId: 48,
    icono: Clock,
    color: 'from-sky-700 to-sky-800',
  },
  {
    id: 'llegadas-tarde',
    nombre: 'Llegadas Tarde',
    descripcion: 'Informe de llegadas tarde por sede, empleado y rango de fechas.',
    ruta: '/dashboard/informes/gestion-humana/llegadas-tarde',
    trimenuId: 49,
    icono: Clock,
    color: 'from-red-500 to-red-600',
  },
  {
    id: 'control-vehicular',
    nombre: 'Informe Control Vehicular',
    descripcion: 'Ingreso y salida de vehículos por portería, con detalle por registro.',
    ruta: '/dashboard/informes/gestion-humana/control-vehicular',
    trimenuId: 54,
    icono: Truck,
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 'mtto-preventivo-vehiculos-propios',
    nombre: 'Mtto Preventivo Vehículos Propios',
    descripcion: 'Reporte de mantenimiento preventivo para vehículos propios.',
    ruta: '/dashboard/informes/gestion-humana/mtto-preventivo-vehiculos-propios',
    trimenuId: 7,
    icono: Wrench,
    color: 'from-cyan-600 to-cyan-700',
  },
  {
    id: 'entradas-salidas',
    nombre: 'Entradas y salidas',
    descripcion: 'Resumen de movimientos de entrada y salida por sede y fecha.',
    ruta: '/dashboard/informes/gestion-humana/entradas-salidas',
    trimenuId: 9,
    icono: LogOut,
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'ingreso-empleados',
    nombre: 'Ingreso de empleados',
    descripcion: 'Reporte detallado de horarios de llegada y salida por empleado.',
    ruta: '/dashboard/informes/gestion-humana/ingreso-empleados',
    trimenuId: 8,
    icono: LogIn,
    color: 'from-amber-500 to-amber-600',
  },
  {
    id: 'informe-tiempo-suplementario',
    nombre: 'Informe Tiempo Suplementario',
    descripcion: 'Listado y análisis de tiempo suplementario (horas extra) por empleado.',
    ruta: '/dashboard/informes/gestion-humana/informe-tiempo-suplementario',
    trimenuId: 6,
    icono: Clock,
    color: 'from-cyan-500 to-cyan-600',
  },
  {
    id: 'informe-pausas-activas',
    nombre: 'Informe Pausas Activas',
    descripcion: 'Control de pausas activas por sede, empleado y fecha.',
    ruta: '/dashboard/informes/gestion-humana/informe-pausas-activas',
    trimenuId: 5,
    icono: Activity,
    color: 'from-emerald-500 to-emerald-600',
  },
  {
    id: 'inasistencia',
    nombre: 'Inasistencias',
    descripcion: 'Consulta y seguimiento de inasistencias del personal.',
    ruta: '/dashboard/informes/gestion-humana/inasistencia',
    trimenuId: 2,
    icono: UserX,
    color: 'from-rose-500 to-rose-600',
  },
];
