import {
  Activity,
  Bike,
  CalendarRange,
  Car,
  ClipboardList,
  Clock,
  ListChecks,
  LogIn,
  LogOut,
  ShoppingCart,
  Truck,
  UserX,
  Wrench,
} from 'lucide-react';
import type { HubItem } from '@/components/shared/hub/types';
import { INFORMES_COPY, INFORMES_GH_TRIMENU } from '@/modules/informes/constants';

export const GESTION_HUMANA_HUB_ITEMS: HubItem[] = [
  {
    id: 'inf-ausentismos',
    nombre: INFORMES_COPY.infAusentismos.title,
    descripcion: INFORMES_COPY.infAusentismos.description,
    ruta: '/dashboard/informes/gestion-humana/inf-ausentismos',
    trimenuId: INFORMES_GH_TRIMENU.infAusentismos,
    icono: CalendarRange,
  },
  {
    id: 'checklist-carro',
    nombre: INFORMES_COPY.checklistCarro.title,
    descripcion: INFORMES_COPY.checklistCarro.description,
    ruta: '/dashboard/informes/gestion-humana/checklist-carro',
    trimenuId: INFORMES_GH_TRIMENU.checklistCarro,
    icono: Car,
  },
  {
    id: 'checklist-moto',
    nombre: INFORMES_COPY.checklistMoto.title,
    descripcion: INFORMES_COPY.checklistMoto.description,
    ruta: '/dashboard/informes/gestion-humana/checklist-moto',
    trimenuId: INFORMES_GH_TRIMENU.checklistMoto,
    icono: Bike,
  },
  {
    id: 'control-compras',
    nombre: INFORMES_COPY.controlCompras.title,
    descripcion: INFORMES_COPY.controlCompras.description,
    ruta: '/dashboard/informes/gestion-humana/control-compras',
    trimenuId: INFORMES_GH_TRIMENU.controlCompras,
    icono: ShoppingCart,
  },
  {
    id: 'indicador-checklist',
    nombre: INFORMES_COPY.indicadorChecklist.title,
    descripcion: INFORMES_COPY.indicadorChecklist.description,
    ruta: '/dashboard/informes/gestion-humana/indicador-checklist',
    trimenuId: INFORMES_GH_TRIMENU.indicadorChecklist,
    icono: ListChecks,
  },
  {
    id: 'indicador-checklist-pesv',
    nombre: INFORMES_COPY.indicadorChecklistPesv.title,
    descripcion: INFORMES_COPY.indicadorChecklistPesv.description,
    ruta: '/dashboard/informes/gestion-humana/indicador-checklist-pesv',
    trimenuId: INFORMES_GH_TRIMENU.indicadorChecklistPesv,
    icono: ListChecks,
  },
  {
    id: 'checklists-equipos',
    nombre: INFORMES_COPY.checklists.title,
    descripcion: INFORMES_COPY.checklists.description,
    ruta: '/dashboard/informes/gestion-humana/checklists',
    trimenuId: INFORMES_GH_TRIMENU.checklists,
    icono: ListChecks,
  },
  {
    id: 'informe-ordenes-salida',
    nombre: INFORMES_COPY.ordenesSalida.title,
    descripcion: INFORMES_COPY.ordenesSalida.description,
    ruta: '/dashboard/informes/gestion-humana/ordenes-salida',
    trimenuId: INFORMES_GH_TRIMENU.ordenesSalida,
    icono: ClipboardList,
  },
  {
    id: 'tallas-personal',
    nombre: INFORMES_COPY.tallasPersonal.title,
    descripcion: INFORMES_COPY.tallasPersonal.description,
    ruta: '/dashboard/informes/gestion-humana/tallas-personal',
    trimenuId: INFORMES_GH_TRIMENU.tallasPersonal,
    icono: ClipboardList,
  },
  {
    id: 'desempeno-empleado',
    nombre: INFORMES_COPY.desempenoEmpleado.title,
    descripcion: INFORMES_COPY.desempenoEmpleado.description,
    ruta: '/dashboard/informes/gestion-humana/desempeno-empleado',
    trimenuId: INFORMES_GH_TRIMENU.desempenoEmpleado,
    icono: ClipboardList,
  },
  {
    id: 'tiempo-gestion-compras',
    nombre: INFORMES_COPY.tiempoGestionCompras.title,
    descripcion: INFORMES_COPY.tiempoGestionCompras.description,
    ruta: '/dashboard/informes/gestion-humana/tiempo-gestion-compras',
    trimenuId: INFORMES_GH_TRIMENU.tiempoGestionCompras,
    icono: Clock,
  },
  {
    id: 'llegadas-tarde',
    nombre: INFORMES_COPY.llegadasTarde.title,
    descripcion: INFORMES_COPY.llegadasTarde.description,
    ruta: '/dashboard/informes/gestion-humana/llegadas-tarde',
    trimenuId: INFORMES_GH_TRIMENU.llegadasTarde,
    icono: Clock,
  },
  {
    id: 'control-vehicular',
    nombre: INFORMES_COPY.controlVehicular.title,
    descripcion: INFORMES_COPY.controlVehicular.description,
    ruta: '/dashboard/informes/gestion-humana/control-vehicular',
    trimenuId: INFORMES_GH_TRIMENU.controlVehicular,
    icono: Truck,
  },
  {
    id: 'mtto-preventivo-vehiculos-propios',
    nombre: INFORMES_COPY.mttoPreventivoVh.title,
    descripcion: INFORMES_COPY.mttoPreventivoVh.description,
    ruta: '/dashboard/informes/gestion-humana/mtto-preventivo-vehiculos-propios',
    trimenuId: INFORMES_GH_TRIMENU.mttoPreventivoVh,
    icono: Wrench,
  },
  {
    id: 'entradas-salidas',
    nombre: INFORMES_COPY.entradasSalidas.title,
    descripcion: INFORMES_COPY.entradasSalidas.description,
    ruta: '/dashboard/informes/gestion-humana/entradas-salidas',
    trimenuId: INFORMES_GH_TRIMENU.entradasSalidas,
    icono: LogOut,
  },
  {
    id: 'ingreso-empleados',
    nombre: INFORMES_COPY.ingresoEmpleados.title,
    descripcion: INFORMES_COPY.ingresoEmpleados.description,
    ruta: '/dashboard/informes/gestion-humana/ingreso-empleados',
    trimenuId: INFORMES_GH_TRIMENU.ingresoEmpleados,
    icono: LogIn,
  },
  {
    id: 'informe-tiempo-suplementario',
    nombre: INFORMES_COPY.informeTiempoSuplementario.title,
    descripcion: INFORMES_COPY.informeTiempoSuplementario.description,
    ruta: '/dashboard/informes/gestion-humana/informe-tiempo-suplementario',
    trimenuId: INFORMES_GH_TRIMENU.tiempoSuplementario,
    icono: Clock,
  },
  {
    id: 'informe-pausas-activas',
    nombre: INFORMES_COPY.informePausasActivas.title,
    descripcion: INFORMES_COPY.informePausasActivas.description,
    ruta: '/dashboard/informes/gestion-humana/informe-pausas-activas',
    trimenuId: INFORMES_GH_TRIMENU.pausasActivas,
    icono: Activity,
  },
  {
    id: 'inasistencia',
    nombre: INFORMES_COPY.inasistencia.title,
    descripcion: INFORMES_COPY.inasistencia.description,
    ruta: '/dashboard/informes/gestion-humana/inasistencia',
    trimenuId: INFORMES_GH_TRIMENU.inasistencia,
    icono: UserX,
  },
];
